function [ output_args ] = csRunAnalysis_Fig8_Connect( cellList )
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here

	csRunAnalysis_Flex(cellList, 'maxRs', 100, ...
		'maxRestSD', 10, ...
		'pulseStart', 500,...
		'maxRm', 1000, ...
		'maxRest', 300); %,...
		%'checkPulseStart', []);
