function [ output_args ] = csRunAnalysis_Fig8_Connect( cellList )
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here

	csRunAnalysis_Flex(cellList, 'maxRs', 70, ...
		'maxRestSD', 10, ...
		'pulseStart', 1000,...
		'maxRm', 2000);
