function [ output_args ] = csRunAnalysis_SecondHalfFig4( cellList )
% csRunAnalysis_SecondHalfFig4
%	has the check pulse in a different place than the standard

	csRunAnalysis_Flex(cellList, ...
		'pulseStart', 1000, ...
		'checkPulseStart', 150, ...
		'checkPulseEnd', 200);
